language: java
jdk:
  - openjdk17

branches:
  only:
    - main

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

before_install:
  - chmod +x gradlew

script: "./gradlew clean build"

before_deploy:
  - zip -r yuseonjun-springboot-webservice ./*
  - mkdir -p deploy
  - mv yuseonjun-springboot-webservice.zip deploy/yuseonjun-springboot-webservice.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

    bucket: yuseonjun-springboot-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait_until_deployed : true
    on:
      branch: main

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

    bucket: yuseonjun-springboot-build
    key: yuseonjun-springboot2-webservice.zip

    bundle_type: zip
    application: yuseonjun-springboot2-webservice

    deplyment_group: yuseonjun-springboot2-webservice-group
    region: ap-northeast-2
    wait-until-deployed: true


# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - seonjun0906@gmail.com